# Automatically generated by GPRPy
import gprpy.gprpy as gp
import fitz  # PyMuPDF
from pathlib import Path

mygpr = gp.gprpyProfile()
mygpr.importdata('/home/renata/ml-gpr/radargrama/FILE__098 P_1.DZT')
mygpr.setZeroTime(0.6)

x_min = min(mygpr.profilePos)           # Tamanho min de X
x_max = max(mygpr.profilePos)           # Tamanho max de X
# Y -- referente ao tamanho setado no 'set Zero Time' e no 'set Y-range', no 'GPRPy'
t_min = min(mygpr.twtt)                 # zeroTime
t_max = max(mygpr.twtt)                 # Max

inicio = x_min
fim = x_max
largura_janela = 1          # X-range
passo = 1                   # deslocamento

i = 0
x = inicio
while x + largura_janela <= fim:
    xrng = [x, x + largura_janela]

    nome_arquivo = f"/home/renata/ml-gpr/frame_{i:02d}.pdf"

    mygpr.printProfile(nome_arquivo, color='gray', contrast=8, yrng=[0,5], xrng=xrng, dpi=600)

    print(f"Gerado: {nome_arquivo}")

    # 6º PASSO - CONVERTER PDF PARA JPG
    # usa biblioteca importada para fazer a conversão 
    doc = fitz.open(nome_arquivo)
    page = doc.load_page(0)
    pix = page.get_pixmap(dpi=300)
    # mudar a string do caminho para o diretório para onde a imagem será salva 
    pix.save(f"/home/renata/ml-gpr/imagens/dzt_098/frame_{i:02d}.jpg")
    print(f"Convertido para imagem: {nome_arquivo}")

    x += passo
    i += 1